server:
  port: 8082
spring:
  application:
    name: provider-ticket
eureka:
  instance:
    prefer-ip-address: true # \u6CE8\u518C\u670D\u52A1\u7528\u670D\u52A1\u5668\u7684IP
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/ # \u6CE8\u518C\u4E2D\u5FC3\u5730\u5740